WITH renamed_and_cleaned AS (
    SELECT  	
        gameId AS                                           game_id,
        playId AS                                           play_id,
        nflID AS                                            nfl_id,
        teamAbbr AS                                         team_abbr,
        hadRushAttempt AS                                   had_rush_attempt,
        rushingYards AS                                     rushing_yards,
        hadDropback AS                                      had_dropback,
        passingYards AS                                     passingYards,
        sackYardsAsOffense AS                               sack_yards_as_offense,
        hadPassReception AS                                 had_pass_reception,
        receivingYards AS                                   receiving_yards,
        wasTargettedReceiver AS                             was_targeted_receiver,
        yardageGainedAfterTheCatch AS                       yardage_gained_after_catch,
        fumbles AS                                          fumbles,
        fumbleLost AS                                       fumbles_lost,
        fumbleOutOfBounds AS                                fumble_out_of_bounds,
        assistedTackle AS                                   assisted_tackle,
        forcedFumbleAsDefense AS                            forced_fumble_as_defense,
        halfSackYardsAsDefense AS                           half_sack_yard_as_defense,
        passDefensed AS                                     pass_defensed,
        quarterbackHit AS                                   quarterback_hit,
        sackYardsAsDefense AS                               sack_yards_as_defense,
        safetyAsDefense AS                                  safety_as_defense,
        soloTackle AS                                       solo_tackle,
        tackleAssist AS                                     tackle_assist,
        tackleForALoss AS                                   tackle_for_a_loss,
        tackleForALossYardage AS                            tackle_for_a_loss_yardage,
        hadInterception AS                                  had_interception,
        interceptionYards AS                                interception_yards,
        fumbleRecoveries AS                                 fumble_recoveries,
        fumbleRecoveryYards AS                              fumble_recovery_yards,
        penaltyYards AS                                     penalty_yards,
        NULLIF(penaltyNames, 'NA') AS                       penalty_names,
        NULLIF(wasInitialPassRusher, 'NA') AS               was_initial_pass_rusher,
        causedPressure AS                                   caused_pressure,
        NULLIF(timeToPressureAsPassRusher, 'NA') AS         time_to_pressure_as_pass_rusher,
        NULLIF(getOffTimeAsPassRusher, 'NA') AS             get_off_time_as_pass_rusher,
        NULLIF(inMotionAtBallSnap, 'NA') AS                 in_motion_at_ball_snap,
        NULLIF(shiftSinceLineset, 'NA') AS                  shift_since_lineset,
        NULLIF(motionSinceLineset, 'NA') AS                 motion_since_lineset,
        NULLIF(wasRunningRoute, 'NA') AS                    was_running_route,
        NULLIF(routeRan, 'NA') AS                           route_ran,
        NULLIF(blockedPlayerNFLId1, 'NA') AS                blocked_player_nfl_id_1,
        NULLIF(blockedPlayerNFLId2, 'NA') AS                blocked_player_nfl_id_2,
        NULLIF(blockedPlayerNFLId3, 'NA') AS                blocked_player_nfl_id_3,
        NULLIF(pressureAllowedAsBlocker, 'NA') AS           pressure_allowed_as_blocker,
        NULLIF(timeToPressureAllowedAsBlocker, 'NA') AS     time_to_pressure_allowed_as_blocker,
        NULLIF(pff_defensiveCoverageAssignment, 'NA') AS                  pff_defensive_coverage_assignment,
        NULLIF(pff_primaryDefensiveCoverageMatchupNflId, 'NA') AS         pff_primary_defensive_coverage_matchup_nfl_id,
        NULLIF(pff_secondaryDefensiveCoverageMatchupNflId, 'NA') AS       pff_secondary_defensive_coverage_matchup_nfl_id

    FROM `nfl-data-dbt.plays.player_play`
),

casted AS (
    SELECT 
        game_id,
        play_id,
        nfl_id,
        team_abbr,
        CAST(had_rush_attempt AS BOOL) AS                       had_rush_attempt,
        rushing_yards,
        CAST(had_dropback AS BOOL) AS                           had_dropback,
        passingYards,
        sack_yards_as_offense,
        CAST(had_pass_reception AS BOOL) AS                     had_pass_reception,
        receiving_yards,
        CAST(was_targeted_receiver AS BOOL) AS                  was_targeted_receiver,
        yardage_gained_after_catch,
        fumbles,
        fumbles_lost,
        fumble_out_of_bounds,
        CAST(assisted_tackle AS BOOL) AS                        assisted_tackle,
        CAST(forced_fumble_as_defense AS BOOL) AS               forced_fumble_as_defense,   
        half_sack_yard_as_defense,
        CAST(pass_defensed AS BOOL) AS                          pass_defensed,
        CAST(quarterback_hit AS BOOL) AS                        quarterback_hit,
        sack_yards_as_defense,
        CAST(safety_as_defense AS BOOL) AS                      safety_as_defense,
        CAST(solo_tackle AS BOOL) AS                            solo_tackle,
        CAST(tackle_assist AS BOOL) AS                          tackle_assist,
        CAST(tackle_for_a_loss AS BOOL) AS                      tackle_for_a_loss,
        tackle_for_a_loss_yardage,
        CAST(had_interception AS BOOL) AS                       had_interception,
        interception_yards,
        fumble_recoveries,
        fumble_recovery_yards,
        penalty_yards,
        penalty_names,
        CAST(CAST(was_initial_pass_rusher AS INT64) AS BOOL) AS was_initial_pass_rusher,
        caused_pressure,
        CAST(time_to_pressure_as_pass_rusher AS NUMERIC) AS     time_to_pressure_as_pass_rusher,
        CAST(get_off_time_as_pass_rusher AS NUMERIC) AS         get_off_time_as_pass_rusher,
        CAST(in_motion_at_ball_snap AS BOOL) AS                 in_motion_at_ball_snap,
        shift_since_lineset,
        motion_since_lineset,
        CAST(was_running_route AS BOOL) AS                      was_running_route,
        route_ran,
        CAST(blocked_player_nfl_id_1 AS INT64) AS               blocked_player_nfl_id_1,
        CAST(blocked_player_nfl_id_2 AS INT64) AS               blocked_player_nfl_id_2,
        CAST(blocked_player_nfl_id_3 AS INT64) AS               blocked_player_nfl_id_3,
        CAST(CAST(pressure_allowed_as_blocker AS INT64) AS BOOL) AS pressure_allowed_as_blocker,
        CAST(time_to_pressure_allowed_as_blocker AS NUMERIC) AS time_to_pressure_allowed_as_blocker,
        pff_defensive_coverage_assignment,
        pff_primary_defensive_coverage_matchup_nfl_id,
        pff_secondary_defensive_coverage_matchup_nfl_id
    FROM renamed_and_cleaned
)

SELECT * FROM casted
