WITH renamed_and_cleaned AS (
    SELECT 
        gameId                                  AS game_id,
        playId                                  AS play_id,
        playDescription                         AS play_description,
        quarter                                 AS quarter,
        down                                    AS down,
        yardsToGo                               AS yards_to_go,
        possessionTeam                          AS possession_team,
        defensiveTeam                           AS defensive_team,
        yardlineNumber                          AS yardline_number,
        gameClock                               AS game_clock,
        preSnapHomeScore                        AS pre_snap_home_score,
        preSnapVisitorScore                     AS pre_snap_visitor_score,
        playNullifiedByPenalty                  AS play_nullified_by_penalty,
        absoluteYardlineNumber                  AS absolute_yardline_number,
        preSnapHomeTeamWinProbability           AS pre_snap_home_team_win_probability,
        preSnapVisitorTeamWinProbability        AS pre_snap_visitor_team_win_probability,
        expectedPoints                          AS expected_points,
        offenseFormation                        AS offense_formation,
        receiverAlignment                       AS receiver_alignment,
        playClockAtSnap                         AS play_clock_at_snap,
        NULLIF(passResult, '')                  AS pass_result,
        NULLIF(passLength, 'NA')                AS pass_length,
        NULLIF(targetX, 'NA')                   AS target_x,
        NULLIF(targetY, 'NA')                   AS target_y,
        playAction                              AS play_action,
        NULLIF(dropbackType, 'NA')              AS dropback_type,
        NULLIF(dropbackDistance, 'NA')          AS dropback_distance,
        NULLIF(passLocationType, 'NA')          AS pass_location_type,
        NULLIF(timeToThrow, 'NA')               AS time_to_throw,
        NULLIF(timeInTackleBox, 'NA')           AS time_in_tackle_box,
        NULLIF(timeToSack, 'NA')                AS time_to_sack,
        NULLIF(passTippedAtLine, 'NA')          AS pass_tipped_at_line,
        NULLIF(unblockedPressure, 'NA')         AS unblocked_pressure,
        NULLIF(qbSpike, 'NA')                   AS qb_spike,
        qbKneel                                 AS qb_kneel,
        NULLIF(qbSneak, 'NA')                   AS qb_sneak,
        NULLIF(rushLocationType, 'NA')          AS rush_location_type,
        NULLIF(penaltyYards, 'NA')              AS penalty_yards,
        prePenaltyYardsGained                   AS pre_penalty_yards_gained,
        yardsGained                             AS yards_gained,
        homeTeamWinProbabilityAdded             AS home_team_win_probability_added,
        visitorTeamWinProbilityAdded            AS visitor_team_win_probability_added,
        expectedPointsAdded                     AS expected_points_added,
        isDropback                              AS is_dropback,
        NULLIF(pff_runConceptPrimary, 'NA')     AS pff_run_concept_primary,
        NULLIF(pff_runConceptSecondary, 'NA')   AS pff_run_concept_secondary,
        pff_runPassOption                       AS pff_run_pass_option,
        NULLIF(pff_passCoverage, 'NA')          AS pff_pass_coverage,
        NULLIF(pff_manZone, 'NA')               AS pff_man_zone

    FROM `nfl-data-dbt.plays.plays`
),

casted AS (
    SELECT
        game_id,
        play_id,
        play_description,
        quarter,
        down,
        yards_to_go,
        possession_team,
        defensive_team,
        yardline_number,
        game_clock,
        pre_snap_home_score,
        pre_snap_visitor_score,
        play_nullified_by_penalty,
        absolute_yardline_number,
        pre_snap_home_team_win_probability,
        pre_snap_visitor_team_win_probability,
        expected_points,
        offense_formation,
        receiver_alignment,
        play_clock_at_snap,
        pass_result,
        CAST(pass_length AS NUMERIC)            AS pass_length,
        CAST(target_x AS NUMERIC)               AS target_x,
        CAST(target_y AS NUMERIC)               AS target_y,
        play_action,
        dropback_type,
        CAST(dropback_distance AS NUMERIC)      AS dropback_distance,
        pass_location_type,
        CAST(time_to_throw AS NUMERIC)          AS time_to_throw,
        CAST(time_in_tackle_box AS NUMERIC)     AS time_in_tackle_box,
        CAST(time_to_sack AS NUMERIC)           AS time_to_sack,
        CAST(pass_tipped_at_line AS BOOL)       AS pass_tipped_at_line,
        CAST(unblocked_pressure AS BOOL)        AS unblocked_pressure,
        CAST(qb_spike AS BOOL)                  AS qb_spike,
        CAST(qb_kneel AS BOOL)                  AS qb_kneel,
        CAST(qb_sneak AS BOOL)                  AS qb_sneak,
        rush_location_type,
        CAST(penalty_yards AS INT64)            AS penalty_yards,
        pre_penalty_yards_gained,
        yards_gained,
        home_team_win_probability_added,
        visitor_team_win_probability_added,
        expected_points_added,
        is_dropback,
        pff_run_concept_primary,
        pff_run_concept_secondary,
        CAST(pff_run_pass_option AS BOOL)       AS pff_run_pass_option,
        pff_pass_coverage,
        pff_man_zone
    
    FROM renamed_and_cleaned
)

SELECT * FROM casted
